### ISSUE TITLE
Add new membership roles

### ISSUE THREAD

**Issue by joshterrell805** [regenerativeag/tools#26]
Adding the new membership roles will require the completion of #16.

We also will need one more piece of data tracked in #16 for the "grace period" rule: we need timestamp when a member transitioned roles, and which roles they transitioned between.

To complete the new roles, we will need to (a) define and implement the new rules and (b) rewrite the config, adding the new roles, and using the new rules.

**Comment by joshterrell805** [comment]
For the rules themselves, I started drafting what the new config can look like. Here is a start:

```yml
roleConfigs:

  # visitor
  - roleId: 0 # (no role)
    paths:
      - period: 60
        rule:
          type: and
          rules:
            - type: has_role
              roleId: <inactiveRoleId>
            - type: react
              emoji: 👍
              messageId: <idOfMessageInQuietGarden>
              removeReaction: true

  # guest
  - roleId: <guestRoleId>
    paths:
      - period: 14
        rule:
          - type: and
            rules:
              - type: has_role
                roleId: 0 # no active role, aka visitor
              - type: post_days
                op: ">="
                value: 1

  # member
  - roleId: <memberRoleId>
    paths:
      - period: 60
        rule:
          - type: and
            rules:
              - type: has_role
                roleId: <guestRoleId>
              - type: post_days
                op: ">="
                value: 4
      - period: 3
        rule:
          - type: and
            rules:
              - type: had_role
                roleId: <activeMemberRoleId>
              - type: post_days
                op: ">="
                value: 1

  # active member
  - roleId: <activeMemberRoleId>
    paths:
      - period: 60
        rule:
          - type: and
            rules:
              - type: has_role
                roleId: <memberRoleId>
              - type: post_days
                op: ">="
                value: 8
              - type: post_weeks
                op: ">="
                value: 4

  # inactive
  - roleId: <inactiveRoleId>
    paths:
      - period: 7
        rule:
          type: and
          rules:
            - type: has_role
              roleId: 0 # visitor (no role)
            - type: no_posts_or_reactions
      - period: 14
        rule:
          type: and
          rules:
            - type: has_role
              roleId: <guestRoleId>
            - type: no_posts_or_reactions
  
  # inactive member

```
